classDiagram
    Inventory <|-- Guitar
    Guitar "1" o-- "1" Inventory
    Guitar "1" o-- "*" Type 

class Guitar {
   note "One game round"
}

class FindGuitarTester {
   note "One game round"
}

class Inventory {
   note "One game round"
}

class Type {
   note "Sequence of games with random generator created at the very beginning"
}

class Wood {
   note "Sequence of games with random generator created at the very beginning"
}

class Wood {
   note "Sequence of games with random generator created at the very beginning"
}




