
classDiagram
    Bet <|-- RedBet
    Bet <|-- BlackBet
    Bet <|-- EvenBet
    SimulationRun "1" o-- "1" Game
    SimulationRun "1" o-- "*" Player
    Player "1" o-- "1" Strategy
    Game "1" o-- "*" Bet
    Bet "1" o-- "1" Player

class Guitar {
   note "One game round"
}

class FindGuitarTester {
   note "One game round"
}

class Inventory {
   note "One game round"
}

enum Type {
   note "Sequence of games with random generator created at the very beginning"
}

enum Wood {
   note "Sequence of games with random generator created at the very beginning"
}

enum Wood {
   note "Sequence of games with random generator created at the very beginning"
}
 
